<!DOCTYPE html>
<html lang="en">

<title>PHYS S-12: Introduction to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">

<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div style="align-items: center; justify-content:center;" class="container-fluid">
    <h3 class="nav-title"> PHYS S-12: Intro to Digital Fabrication</h3>
    <div class="navbar-nav">
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../finalproject.html">Final Project</a></h4>
      <h4><a class="nav-link" href="../about.html">About</a></h4>
    </div>
  </div>
</nav>

<body>


<xmp style="display:none;">
<br> 

<h1>Press-fit Construction Kit</h1>
  <p>For my press-fit construction kit, I decided to go with a celestial theme. I wanted to create three shapes of varying difficulties. I had one simple shape, one medium difficulty shape, and one extremely difficult shape. So I chose to make a sun, a crescent moon, and a star. (I know the sun is a star, but a circle was the simplest shape I could think of.) I did my best to make my shapes around 80 mm each.</p>

  <h2>Simple Difficulty Shape: Sun</h2>
    <ol>
        <li>Open Fusion 360, then select the top icon of the 3D Box <img src="./02_design/Photos/screenshot(5).png" alt="Image 1"></li>
        <li>Select Sketch Button</li>
        <li>Select the orange square</li>
        <li>Type C or Click Center Diameter Circle</li>
        <li>Select Center Origin & Draw line to 80 mm</li>
        <li>Zoom Into the Circle</li>
        <li>Select Line & Put cursor till it forms an x on the circle circumference- draw the line out to 4.8 mm (cardboard depth)</li>
        <li>Draw a new line from the end of the line to the center (click on the green guideline)</li>
        <li>Hover mouse over to the left and this time type the length equal to the segment you just drew (in my case 0.929 mm)</li>
        <li>Lastly hover your mouse over the circle circumference at the spot where it matches the length of the other segment you drew (4.8)</li>
        <li>Zoom in and Click Create and then Click Circular Pattern</li>
        <li>Now Click each of the 4 lines that make up the indent</li>
        <li>This should be the result</li>
        <li>Now click on the center point</li>
        <li>Click on the origin</li>
        <li>Increase Quantity to 4 & Click Ok</li>
        <li>Click Finish Sketch</li>
        <li>Double-click inside the circle</li>
        <li>Click Extrude type in 4 mm</li>
        <li>Click ok</li>
        <li>Click the arrow below the top box</li>
        <li>Click on Select and click the two edge lines - click one line and then hold control and click on the other line</li>
        <li>Click Fillet under Modify</li>
        <li>Type in 1mm and click ok - Repeat for all the other edges</li>
        <li>Click on the top arrow</li>
        <li>Click on the surface tab and click the top surface</li>
        <li>Click on offset under create</li>
        <li>Type in 3mm for the distance and then click ok</li>
        <li>Click on the sketch tab and right-click the sketch inside</li>
        <li>Select save it as a DXF</li>
        <li>Lastly, save it to your computer</li>
    </ol>    

  <h2>Medium Difficulty Shape: Crescent Moon</h2>
    <ol>
        <li>Repeat the first 5 steps of the last tutorial</li>
        <li>Click create and under arc click center point arc</li>
        <li>Click the leftmost point on the circle, then the highest point, then the lowest point</li>
        <li>Next, click the select button and then the line we just created</li>
        <li>Now using your mouse, drag out the line</li>
        <li>Select trim (the scissors) and click on the leftmost line. It should highlight purple, and then disappear</li>
        <li>Now select the line tool and draw a vertical line that is 0.929 mm starting at the red guideline</li>
        <li>Now starting at the top point of the line we just drew, using the same tool we are going to make another line that is also vertical and 0.929 mm</li>
        <li>Create another line, using the same tool, that is horizontal and 4.8 mm. Start the point at the top most point of the previous line.</li>
        <li>Do the same things except at the bottom, using the bottommost point</li>
        <li>Now using the select tool, select the top line, and then while holding control, select the other three lines</li>
        <li>Hover your mouse over one of the lines and drag it so that the two vertical lines meet the circumference</li>
        <li>Now we will create another notch on the other side. First, we will use the select the line tool and draw a vertical line that is 0.929 mm starting at the red guideline</li>
        <li>Now starting at the top point of the line we just drew, using the same tool we are going to make another line that is also vertical and 0.929 mm</li>
        <li>Create another line, using the same tool, that is horizontal and 4.8 mm. Start the point at the topmost point of the previous line.</li>
        <li>Do the same things except at the bottom, using the bottommost point</li>
        <li>Now using the select tool, select the top line, and then while holding control, select the other three lines</li>
        <li>Hover your mouse over one of the lines and drag it so that the two vertical lines meet the circumference</li>
        <li>Click Finish Sketch</li>
        <li>Double click the moon and then click extrude</li>
        <li>Type in 4 mm and then click ok</li>
        <li>Click the arrow below the top box</li>
        <li>Now click the left arrow by the front box</li>
        <li>Click on Select and click the two edge lines - click one line and then hold control and click on the other line - then click fillet under the modify tab</li>
        <li>Type in 1mm and click ok</li>
        <li>Click the left arrow twice on the box</li>
        <li>Now repeat the same process that you did for the other indent</li>
        <li>Click the top arrow</li>
        <li>Click on the surface tab and click the top surface</li>
        <li>Click on offset under create</li>
        <li>Type in 3mm for the distance and then click ok</li>
        <li>Click the eyeball to hide Body 1 to leave you with just the 2D disk</li>
        <li>Click on the sketch tab and right-click the sketch inside</li>
        <li>Select save it as a DXF</li>
        <li>Lastly, save it to your computer</li>
    </ol>   

  <h2>Hardest Difficulty: Star</h2>
    <ol>
        <li>Repeat the first three steps of the circle tutorial</li>
        <li>Select edge polygon under the polygon tab under the create tab</li>
        <li>Set your first point as the center point</li>
        <li>Draw the line out and set it to be 30 mm</li>
        <li>Add 5 Sides</li>
        <li>Use l to select the line tool, then select the top most point as the start point. Then draw out the line (the length does not matter - just make it very long)</li>
        <li>Using the last line as a marker of the midpoint, we are going to draw two more lines to make the points of the triangle.</li>
        <li>Once again use l to select the line tool, then select the left point of the bottom line. Set the length to be 30 mm and then click on your guideline to connect it.</li>
        <li>Do the same with the right point.Use l to select the line tool, then select the right point of the bottom line. Set the length to be 30 mm and then click on your guideline to connect it.</li>
        <li>Use the select tool to choose one of the sides you just drew, then hold down control to select the other side that you just drew</li>
        <li>Select Create tab and then click circular pattern</li>
        <li>Set the center point as the center of the pentagon and then set the quantity to 5 and then click ok</li>
        <li>Using the select tool you can now choose the five inside lines and delete it using backspace</li>
        <li>Now, we need to add the indents. Using the line tool create a horizontal line that is 0.929 wide. This line will start at the guideline.</li>
        <li>Use the line tool to create a horizontal line that is 0.929 wide. This line will start at the guideline where the end of the line we just drew is and go towards the left</li>
        <li>Use the line tool to draw vertical lines that are 4.8 mm long. Each one will start at one of the ends of the horizontal lines.</li>
        <li>Using the select tool select all four lines and then drag the points to meet the ends of the star</li>
        <li>Using the select tool select all four lines once again. Then go to the create tab and then the circular pattern tab</li>
        <li>Select the center point as the origin point. Set the quantity to be 5 then hit ok.</li>
        <li>You can know use select and backspace to get rid of the guideline Then click finish sketch</li>
        <li>Double-click the star and then click extrude</li>
        <li>Type in 4 mm and then click ok</li>
        <li>Click the arrow below the top box</li>
        <li>Click on Select and click the two sets of two edge lines - click one line and then hold control and click on the other line - then click fillet under the modify tab</li>
        <li>Type in 1mm and click ok</li>
        <li>Click the left arrow on the box</li>
        <li>Now repeat the same process that all of the other indents. You donâ€™t have to do multiple at a time if you do they do not all show on your screen.</li>
        <li>Click the top arrow</li>
        <li>Click surface tab and then the star</li>
        <li>Click on offset under create</li>
        <li>Type in 3mm for the distance and then click ok</li>
        <li>Click the eyeball to hide Body 1 to leave you with just the 2D disk</li>
        <li>Click on the sketch tab and right-click the sketch inside</li>
        <li>Select save it as a DXF</li>
        <li>Lastly, save it to your computer</li>
    </ol>
<h1>Fusion 360 Tutorial</h1>
  <p>For this part of the assignment, I decided to use one of the given tutorials.</p>
    <a href="https://www.youtube.com/watch?v=vVFYrBClkPc">Fusion 360 Tutorial for Beginners - 1</a>
  <ol>
    <li>The first step was to create a sketch and then select the top plane.</li>
    <li>Next, use the line tool to make a horizontal line that is 70 mm long, then a diagonal line 70 mm at an angle of 120 (use tab to switch here). While holding down the right side of the mouse, you can drag out to make an arc</li>
    <li>Draw the line down until the blue guides show up</li>
    <li>Lastly draw a horizontal and vertical line to close up the shape</li>
    <li>Under sketch select sketch dimension</li>
    <li>Select the line and then draw it out to find its measurement</li>
    <li>Using the same tool, you can select two lines to find the angle measure</li>
    <li>You can also select the circle to get its radius</li>
    <li>If you scroll with your mouse, then you can zoom inwards and outwards. If you click the hand icon at the bottom, then you can use it to move the screen around. If you click and drag, a square will be created and that can be used to select your entire object</li>
    <li>Under the options tab, you can click construction (under linetype) - this will allow you to make reference lines by using the line tool in the same way as always</li>
    <li>The video then has us draw guidelines</li>
    <li>Click c to make a circle and then draw two circles using the origin and the furthest horizontal point as your centers</li>
    <li>Use the line tools to make two lines connecting your circles.</li>
    <li>Use ctrl and select to choose a circle and a line and then select tangent under constraint. The tangent symbol should then appear</li>
    <li>Now select trim to get rid of the inside circle lines</li>
    <li>You can select zoom window to get a closer look and get rid of any extra lines</li>
    <li>The tools at the bottom can be used to zoom in and out. The buttons at the top can be used to save, redo, and undo.</li>
    <li>If you select two objects, and then select coincident (under the constraint tab), you can align them.</li>
    <li>Then the video has us delete everything again using the drag function.</li>
    <li>The last thing the video teaches is how to create an ellipse and measure it. Under the sketch tab, select ellipse, then set the origin as the center. Drag out the lines and click to create the shape.</li>
    <li>You can press D on your keyboard, click a line and then move your mouse to find the measurement</li>
  </ol>
<h1>Household/Lab Component 3D Recreation</h1>
  <p>The household/lab component items that I decided to create were a 5 volt USB plu g and a coin battery.</p>
  <h2>5 Volt USB Plug</h2>
    <ol>
      <li>The first thing I did was enter sketch mode and then select the top face. The I used the rectangle tool, made the center my origin, then dragged out horizontally and clicked. Then I typed in 54.41 mm for my length and then hit tab and typed in 35 mm for my width and then clicked finish sketch.</li>
      <li>I changed the viewpoint to the front by clicking the arrow below the top box. Then I clicked extrude, selected the box, and typed in 20.14 mm.</li>
      <li>Now I am going to create the metal teeth. Select create a sketch again. Draw a rectangle using the rectangle tool. Type in 15 mm for the length and 6.09 mm for the width. Click finish Sketch and rotate it on its side using the move tool.</li>
      <li>Click extrude, select the newly drawn shape, and type in 1.43</li>
      <li>Zoom in, select the create a whole tool, click where you want your hole to appear, doing your best to center it, and then type in 1.42 and click ok.</li>
      <li>Drag out and select the body - copy and paste it</li>
      <li>Now move to the left view (using the box) and move the prongs to the place shown in the image. You can use the inspect tool to confirm you have the correct width</li>
      <li>Now we need to add the USB port. Enter the right view and select shell. Type in 7.09 mm. Then use the select tool to select the inside of your hole and then click the move tool and move it closer to the edge.</li>
      <li>To create the inside part of the USB. Use the box tool under the create taband make it 18mm  x 47.32 mm x 2 mm</li>
      <li>Then use the move tool to place the your new box inside the hole in your plug.</li>
      <li>The last thing we need to add is the ridges. To do this we are going to use the fillet tool. Select the shown edges and type in 2 mm</li>
      <li>In the back view do the same thing but type in 0.6 mm. Do the same for the last 4 edges and type in 1.5 mm</li>
    </ol>
  <h2>Coin Battery</h2>
    <ol>
      <li>The first thing I did was enter sketch mode and then select the top face. Next, I used c, to select my circle tool, placed my center point at the origin, and made the diameter 19.81 mm</li>
      <li>I used C again, to select my circle tool, then I placed my center point at the origin, and made the diameter 17.65 mm to form the inner ridge of the battery and clicked finish sketch. (I ended up moving the inner circle to the side)</li>
      <li>I clicked the arrow below top to switch to front view. Then I clicked extrude and put in 2.82 mm. I did the same for the smaller circle, except I only extruded it 0.37 mm.</li>
      <li>Next (with some assitance) I used the move tool to target the bottom plane of my small circle and the top plane of my big circle and moved them on top of each other.</li>
      <li>Next, using the select tool, I selected the top edge of my bigger circle, then went to modify and pressed f for fillet - then I put in 0.62 mm. I repeated this for the bottom edge of the my bigger circle and put in 0.48 mm</li>
      <li>Lastly, I added another fillet (using the same process) to the top edge of the top circle, and made it 0.2 mm</li>
    </ol>

</xmp>
</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>