<!DOCTYPE html>
<html lang="en">

<title>PHYS S-12: Introduction to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">

<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div style="align-items: center; justify-content:center;" class="container-fluid">
    <h3 class="nav-title"> PHYS S-12: Intro to Digital Fabrication</h3>
    <div class="navbar-nav">
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../finalproject.html">Final Project</a></h4>
      <h4><a class="nav-link" href="../about.html">About</a></h4>
    </div>
  </div>
</nav>

<body>


<xmp style="display:none;">
<br> 

<h1>Rising Tower </h1>

This we week we were asked to create a kinetic sculpture. So, I decided to make a tower with a small coat of arms that would bob up and down.

<h2>Instructions</h2>

<ol>
  <li>The first thing I did was use the rectangle tool to create a 127 cm x 40 cm rectangle<img src="https://lh3.googleusercontent.com/QROAfcFwxbFG5cQZ_r57aIyva21jnvxhQisJz58oZlT68-l7lF1QcvoXBGpeq0pXKcIZeyT3mcj08JChqL4LmAdqHXb7bZMHRDgTyIzG5uighF_Aa4K5LZTWNIyc7wUGzulGkiKmOh9PheUxbVUuwZI" alt="Image 1" width="640" height="360"></li>
  <li>Then I made two vertical 1 cm lines that extend from the top corners<img src="https://lh6.googleusercontent.com/7OnlLb8pyhmrJB0UmnLTiQNsftD-PFa9wPOIIlwhn1rl6ARKGHzwED2URWM48VfdjrJ3Sp1Ko7jesVVi7O5cZpmfnOVuiXI0vgeCj2l0zGGYcQvECQ9fy1MCqWDLLw3R38WVXlatp-GCIz_0mD2zAvs" alt="Image 2"width="640" height="360"></li>
  <li>Then, I made a horizontal line 5 cm long on each of the corners, drew a vertical line down, and then drew a horizontal line 8 cm long, and drew them up again.<img src="https://lh5.googleusercontent.com/OvSvxPSd_z2Rfsuf9vjJMnQxy4ypwe6ukCRszEROjdtAC79_eKDrAtlOKgMjrN-8i-c9tKDi6Ty8XpRgODYv6HWCy1-UJ1ObQdxoYGgWTBGKAPBcsAJmLiyKX12MJ7SXefxXwLYQUuv89a2FwS6N9Mc" alt="Image 3"width="640" height="360"></li>
  <li>Then you can cut out the extra lines<img src="https://lh5.googleusercontent.com/WIKytYMv1ee_W5kirFL8Q4Z89tnt4K4QyK1D-crZqpDy4u_0Uv7lSsLtG-oXo0jrqMa_VCmQxH0iuz_0aECyD-Bn3z4d8gpgGSXwdTZ_tOVg2FWBbch0YsJGdLaw3tmT3gk8i5Q_3XVoDrYlG-6ped0" alt="Image 4"width="640" height="360"></li>
  <li>Now, we just need to add the notches to make all the pieces fit together. First, I created 10 guidelines that are 10 cm apart<img src="https://lh4.googleusercontent.com/SIKkH-e4EluC66qGSCPFAgQ1XCke7VXA7jmidtWKzbgI18aA5hZVx1oIXflPpw8O5JeXmr5UxGJZv1G3r7WDYH085KY88UslCPc8wzQzGJnXFg40foPLmS6aoAiS3qrDphc8ZJi8HNwlkbqf3bTDz9o" alt="Image 5"width="640" height="360"></li>
  <li>Then I used the line tool to create notches that are 3.8 mm by 10 mm<img src="https://lh5.googleusercontent.com/LGUfIAAf63zeBAp4WzTPxBKJhX3ONpaVZAuo-F9F17JMyvTqq4eAIj__Rjb0n06Wzj9NXAwpr0FYxUUH5rAMuPUo9VSBqmw1SHaWUHqhejKgaTr75_Ip4d4QSN_95w_NBaA4XhFsXhvQsGZlP4WNhmE" alt="Image 6"width="640" height="360"></li>
  <li>Now I can create another rectangle and repeat the same process but put the notches on another level.<img src="https://lh3.googleusercontent.com/C69y78eRGEWETf50sVX_4tcsvT30ljmtN8jS_G9xzGDv1ZBGgMXTRJYaX-x1ntkg-0bBs2lEKYh6qkDiNFUWPwIGch5Ou5Pbkif8Vn5FJgH59oMLnqI2C6pX9DHho71AdHBMyL6tOCuJMtKo1BkrRh0" alt="Image 7"width="640" height="360"></li>
  <li>Now I will erase the guidelines and remove the excess lines and connect any gaps<img src="https://lh4.googleusercontent.com/6fD89Ugm2mVhm3q9dGEhygXN5dzpLIJRQCLqcUz8s5juWWPf_WeftiElxdUeZCddw-pdfwBcFI3PKS7KFrgOSst0-KOZ4WcGvGlF5GOiMd4--xUkac8pQusgQs2vpoJCyBhw18EVr5Fv22SILVkWxnw" alt="Image 8"width="640" height="360"></li>
  <li>The next thing to do is create the coat of arms that will move up and down. Use the line tool, the center arc tool and the mirror tool to create a shape like this. It consists of horizontal 20 mm line, two vertical lines 15 mm long, and a tangent line about 17.8 mm long.<img src="https://lh3.googleusercontent.com/c0e_L4ySp9S0tRAyzFkOfj8P05AHpe1RoeY1SFvKVEYdKcEYyfZ49YWrYKbyvEdw4rBDnp236-U1ennC57M_Iia47nEOn7ghXLR6X1KngB4YY_iJDyftH_PqH7Kfhgp2WZ4cJauidCrDAgUiADH2zac" alt="Image 9"width="640" height="360"></li>
  <li>Copy and paste the shape and then use the scale tool under modify and set it to 0.8. Then, you can move the shape on top of the original shape.<img src="https://lh6.googleusercontent.com/oUOm9RdmZGiHFMxGrwshiinsJhK7xcEz3Yig_ZH8vad1WnfjX4rObwXKOlU6RHMhhph4TU8a1QjbmR48FMiIllPKsKvM0qYkUhf3RTto0EXg_dgHb6bI7URoL2mdFipj3gic_4jCtzsmbXYLK9VUYyg" alt="Image 10"width="640" height="360"></li>
  <li>To create the base of the structure make a square that is 38.5 x 38 inside make a 3.3 square<img src="https://lh5.googleusercontent.com/i4rCJejRUYFbe2yiQZHdCtYv5bYtaQdWiKni7Xf1CWURFR1xHVAfGuQIFIw38UCDi2OQTKVHpLwU_XQ8Vp1p4zlX-RUmguLHRthQnbTIkiD9xpKjm60Z7uKSfWUXfLIhgH0T8Obbw7aQLPF5IsiXpgc" alt="Image 11"width="640" height="360"></li>
  <li>To create the housing box, make squares of 110 mm by 110 mm using the rectangle tool. Then, add the joints by alternating cutting and adding small rectangles.</li>
  <li>To make the bottom plate of the castle, make a square 38 mm by 38 mm. Next, add a rectangle of approximately 3.3 mm by 3.3 mm in the center.<img src="https://lh5.googleusercontent.com/RkP_IjSZXF1CsjwN2ovtHk_KHKJYFd8S5IM03PdZAxzMxoL0YHioXaIDD9rNMdoT0tOy7IzfGy2MVEoo7LqxLHTJX9wjrv290cImEDI9ewH8yh_vQ4MimRA8a8tM8jBxh32fNStqpIxLuY1MFA1z5po" alt="Image 12"width="640" height="360"></li>
  <li>We need to create two gears next. Create a circle 15.5 mm in diameter. Create another circle 36 mm in diameter. <img src="https://lh3.googleusercontent.com/G-3LnItOo0I0RwXXRsKgNvlp0Ut6UUEI8UOPwB1zvETLnQcWIjvvKXdyWbWnPtxeMH36g8qsmZbZ00HDPZ155i20rshSq-LJT1GJNkM7_5RG46tUcAU94a8owsxelDW7qfGSmllPk3_nrV_MjzOJVFA" alt="Image 13"width="640" height="360"></li>
  <li>Use the line tool to make a pentagonal shape with a 1.44 mm top, 3 mm side, and roughly 2 mm side. Then move that shape on to the circle.<img src="https://lh4.googleusercontent.com/CDHHqjoqkWgDAaez3vv0LK2O7zgai_y7rPcPl-UQhOtGLnTjy4I7JqrgbaV8tkTaAkmZ-99sH-TEXZjVA3LJuc5ftGaaCTJlj2rxqPSiqkdUqoCGpI-PfmS9sdmcaqPwrUUSedTqy-01RWGwl7C5-W0" alt="Image 14"width="640" height="360"></li>
  <li>Select the gear tooth shape and then select circular pattern and make 8.<img src="https://lh5.googleusercontent.com/Y2tcKh3cZg00yDcER2jjuGu8gi5cGjwA7tzCzqbrV49j94-BHaroD0u5KVssl94aaxpuvPzUlYr_j0B2gnOz_sAVkG5CHUeMb9gTPR3kKLMOtdyeIzN_u6mOp7ylBhkHEFq-A09WsdR2fb8pWfglOhU" alt="Image 15"width="640" height="360"></li>
  <li>Then copy and paste the gear tooth shape and scale it up so the bottom is around 4.1 mm. Move it onto the the larger circle<img src="https://lh6.googleusercontent.com/iOnStVOU4pUkT8qLAkM0q08Z4IECY-SM8JZ7F4pxQcnbOqfk8Qu3waejGS7WmpG6AUU7tQXMeXsnmReZTbQVmKoq3nWoKHIQeOASbSylf6SdIHhtOltxSfTkhfithFtfcuw_QGmq4kHJSqeKdY2qOf8" alt="Image 16"width="640" height="360"></li>
  <li>Select the gear tooth shape and then select circular pattern and make 16<img src="https://lh6.googleusercontent.com/USFhNEC3k0JDvCKBXECmX1s_u6RqvY64ouEIZnXI5b_ao5_lqYz-WGdMKQ2ORNVBAXamgh-SajyKDf3-8BmGAoW7vgq1KzcEcOPsQ0WWLRheeIqKfvQcBrCJ71HCdZdEO_dCm0Nu6E9LRuOZ0hVufYE" alt="Image 17"width="640" height="360"></li>
  <li>Make a circle 4.6 mm in diameter in the center of the smaller gear and remove any excess lines with the trim tool<img src="https://lh3.googleusercontent.com/D_B-TKySqdsu-FL88_aDpbCIvytXBfmpvHj9Mds5b82xYs_q7IUjhdiK6CkJQQ167xyIn_1GMXOjj0dr6C0n_ivOs_44iSFLKoaY2Nx9zOkd3ZC05oSBsPEbqCGOiJkhPVBBotQRNswAse_gq_qzUVk" alt="Image 18"width="640" height="360"></li>
  <li>Make a circle 4.74 mm in diameter in the middle of the bigger gear and get rid of any excess lines<img src="https://lh3.googleusercontent.com/TVS1-1Y7QaoMnHokYUrvTMT-LMbm6h3Vt2pkIwpeV9nozouPClGUT6YAneqFqvZS-nY2bWEvAlp20iOnFPfqsKTFZP3bS4B9IAlj82Ea6nfy7YcoVITvZjJMkRJo-EYi1VE7muv3Xy34RI2Md9grrC0" alt="Image 19"width="640" height="360"></li>
  <li>To make the cover circle for the bigger gear create a circle that is 30.1 mm in diameter. Then create a circle that is 4.74 mm in diameter in the center of that circle. Then create a circle 4.2 mm in diameter that is off-center and is 1.3 mm from the edge.<img src="https://lh4.googleusercontent.com/-3hdvRMAa2B-OTLMfLiPCRPeBQ7u9-LNygq8W4chFq4AmN9lYlbXIVSdb--EWOMsyEPs6fuubigigBDwwMktVVFoHDtBkB7KD2GlNpO31LyHTuGoWCzJNnS9x-2OOf5PfV_xHw_U1eH90IRWX9a6W04" alt="Image 20"width="640" height="360"></li>
  <li>To create your securing pegs make a trapezoid with a base of 3.3 mm and 4.02 mm with side lengths of 13.507 mm. Create a circle 9.3 mm in diameter. In the center make a 2.4 mm by 2.3 mm rectangle. Then combine the two shapes and trim any extra lines<img src="https://lh3.googleusercontent.com/7oapu1uE7N21Znl3w5trg5GrzVKMnUTYhGnsWVcfvbXu31sgRJ5oRhA206pFsmA-RWx4TQFJHvE3-TlZcDTYAsoZGECNKMTce9v3Aiv8YrY7BLHZdo-j7UrWXMvD_jjPdXgs7DnPZIT2pgAjAwAf9ec" alt="Image 21"width="640" height="360"></li>
  <li>Then duplicate the shape and replace the inside rectangle witha  circle that is 4.85 mm in diameter<img src="https://lh5.googleusercontent.com/R-nD5w95IBPxUY6_PiCbNRP-RdyuzTYbmgbI5BGQbQZIYn0WLnix7JrBkXTt7Y_p7BEtZxcCkWI3a5RYjZqbmae89vPVnCn1dw6O4oKxwJmaJkgCruBrYc8kjUov-un2jW6YfgIlP1yqukf63pEXyBg" alt="Image 22"width="640" height="360"></li>
  <li>To create your support box create rectangles using the rectangle tool and lines to create the notches. In the top box create a square that is 38 mm by 38 mm<img src="https://lh6.googleusercontent.com/sr1hHJwiss7FRVvdjGBDlP64PReuj32jDcYyyK-gRq_iLP3GumxXINUDlffiWssKoLTN6jwNy7ZvBcys6_crVv_x69HbmE-f-zyHnONRBVbieFv5edTvIvZ9xFLQcWAacxztOR8-12zhrsliV00it6E" alt="Image 23"width="640" height="360"></li>
  <li>For the inside panel, create a square that is 102 mm by 101 mm.</li>
</ol>

</xmp>
</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>